# Form implementation generated from reading ui file 'Dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UI_Dashboard(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        app_icon = QtGui.QIcon()
        app_icon.addPixmap(QtGui.QPixmap("images/pbi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(app_icon)
        self.content = QtWidgets.QGridLayout(Form)
        self.content.setObjectName("content")
        self.image = QtWidgets.QLabel(Form)
        self.content.addWidget(self.image, 0, 0, 1, 1)
        pixmap = QtGui.QPixmap("images/dashboard.png")
        self.image.setPixmap(pixmap)
        self.image.resize(pixmap.width(), pixmap.height())
        self.image.setObjectName("dashboard")
        self.image.setScaledContents(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Excel Dashboard"))
